"""create history table

Revision ID: d89a07c189a1
Revises: 8db971dead91
Create Date: 2024-11-01 23:56:35.063455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd89a07c189a1'
down_revision: Union[str, None] = '8db971dead91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hystory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_key', sa.String(), nullable=True),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hystory_chat_key'), 'hystory', ['chat_key'], unique=False)
    op.create_index(op.f('ix_hystory_id'), 'hystory', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hystory_id'), table_name='hystory')
    op.drop_index(op.f('ix_hystory_chat_key'), table_name='hystory')
    op.drop_table('hystory')
    # ### end Alembic commands ###
